---
- name: Hardering para Servidores Ubuntu
  hosts: ubuntu
  become: yes

  tasks:
  - name: Permitir trafico saliente
    community.general.ufw:
      policy: allow
      direction: outgoing

  - name: Bloquear trafico entrante por defecto
    community.general.ufw:
      policy: deny
      direction: incoming

  - name: Permitir trafico SSH
    community.general.ufw:
      rule: allow
      name: OpenSSH

  - name: Asegurar que ufw este habilitado
    community.general.ufw:
      state: enabled

  - name: Asegurar que exista clave publica para el usuario sysadmin
    ansible.posix.authorized_key:
      user: sysadmin
      state: present
      key: "{{ lookup('file','~/.ssh/id_rsa.pub') }}"

  - name: Deshabilitar autenticacion por contraseña en SSH
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: "^PasswordAuthentication"
      line: "PasswordAuthentication no"
      state: present
    notify: Reiniciar SSH


  handlers:
  
  - name: Reiniciar SSH
    ansible.builtin.systemd_service:
      name: ssh
      state: restarted